############################
## CHANGE THESE
############################

baseURL: "https://sebviolet.github.io/hugo-qubt"
title: hugo-qubt

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
